---
- hosts: tools
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    # Gitlab
    - name: Instando dependencias [ Gitlab ]
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - curl
        - openssh-server
        - postfix
        - ca-certificates

    - name: Baixando o script de intalacao [ Gitlab ]
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/script.deb.sh

    - name: Executando o script [ Gitlab ]
      command: bash /tmp/script.deb.sh

    - name: Instalando [ Gitlab ]
      apt: name=gitlab-ce update_cache=yes state=present
