---
- name: tools
  box: trombik/ansible-ubuntu-16.04-amd64
  hostname: tools.devops.com.br
  ipaddress: 192.168.1.10
  memory: 2048
  cpus: 2
  provision: provision/ansible/base.yaml

- name: dev
  box: trombik/ansible-ubuntu-16.04-amd64
  hostname: dev.devops.com.br
  ipaddress: 192.168.1.20
  memory: 2048
  cpus: 2
  provision: provision/ansible/base.yaml

- name: qa
  box: trombik/ansible-ubuntu-16.04-amd64
  hostname: qa.devops.com.br
  ipaddress: 192.168.1.30
  memory: 2048
  cpus: 2
  provision: provision/ansible/base.yaml

- name: prod
  box: trombik/ansible-ubuntu-16.04-amd64
  hostname: prod.devops.com.br
  ipaddress: 192.168.1.40
  memory: 2048
  cpus: 2
  provision: provision/ansible/base.yaml

- name: monitoring
  box: trombik/ansible-ubuntu-16.04-amd64
  hostname: monitoring.devops.com.br
  ipaddress: 192.168.1.50
  memory: 2048
  cpus: 2
  provision: provision/ansible/base.yaml
...
